test-pod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
spec:
  selector:
    matchLabels:
      app: ms
  replicas: 1
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: rachitsrivastava007/sleep:8
        ports:
        - containerPort: 80
        args:
            - -c
            - while true; do echo hello; sleep 10;done
        command:
            - /bin/sh

