apiVersion: v1
kind: Service
metadata:
  name: my-app-blue
  labels:
    app: my-app-team-y
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app-team-y
    version: v2.0.0
