SHELL := /bin/bash

initialSetup: 
	source recreate.sh;startDeployment

deployment:
	source recreate.sh;recreateDeployment

rollback:
	source recreate.sh;rollback

tearDown:
	source recreate.sh;cleanUp

